### ISSUE TITLE
update to v5 namespace link

### ISSUE THREAD

**Issue by danlentz** [Yuppiechef/cqrs-server#4]
I've done some work on clj-uuid and cleaned up the v3/v5 implementation quite a bit as well as putting together some brief overview on basic use at http://danlentz.github.io/clj-uuid  -- if it helps, please feel free to link to the current version of http://github.com/danlentz/clj-uuid

Best,
Dan

**Comment by CmdrDats** [comment]
Hi Dan,

Fantastic, thanks for letting me know - I will upgrade as soon as I get a chance :) Thanks for putting together a great library!

Cheers,
 - Deon
